### PR TITLE
Icons hover style, scrollable toolbar on detail view, replicate icon fix, icon aligment on table row, introduced nova-packages-tool

### LINKED ISSUE #13: Wrong link to replicate method
Hello,

when resource is allowed to replicate, there is Replicate icon,
image

but clicking it causing 404 due to wrong uRL:
image

### LINKED ISSUE #14: Clicking on the checkbox selection causes layout shift
Hello,

as on video:

https://github.com/user-attachments/assets/08ae0752-5cc5-4f5e-bef1-0a016b0bae17

### LINKED ISSUE #15: Double delete buttons
I works fine on normal index view, but in lens index view or has many relation index view it renders 2 delete buttons with only the right one working.

image

### PR DESCRIPTION
**Pull request by webard**
closes #14 
closes #13

- Fixed icon hover styles
- Made the toolbar scrollable on the detail view for mobile when there are many actions:
image

- Fixed the replicate action link #13 
- Adjusted icon alignment in table rows
- Introduced `nova-packages-tool`, reducing the production size of tool.js from 823 KB to 256 KB

### CODE REVIEW

**Comment by milewski** [comment]
On details page the scrollbar is always visible... 

image

**Comment by milewski** [comment]
The icons also stopped showing on the index view ... using the latest nova version https://nova.laravel.com/releases/4.35.2

**Comment by milewski** [comment]
Uhm, I meant this one stopped showing to me:

image

The ones marked in green are okay, the red one is not showing...

**Comment by webard** [comment]
The icons for multiple actions are working fine, and I’ve even adjusted the background color to match the new color from Nova:image

However, I have no idea how to configure these actions:
image

even in the original package, without the PR.

**Comment by milewski** [comment]
Okay, I will test it again tomorrow, thanks!

**Comment by webard** [comment]
Okay, thank you.

This PR closes this issues
#14 
#13

I would appreciate it if you could take a look at this issue: #15 

image

This occurs with BelongsToMany relationships on the resource page.
Unfortunately, I was unable to find the cause of the problem.

**Comment by milewski** [comment]
Sorry the delay, it was a long holiday in China.. just got back to work, it seems all good now, I fixed the double delete button issue.

Thanks!

**Comment by milewski** [comment]
> However, I have no idea how to configure these actions: image
> 
> even in the original package, without the PR.


I forgot that set of icons on the left was part of another package: https://github.com/dcasia/batch-edit-toolbar

**Comment by sysyl** [comment]
Hello @milewski ,
Thanks for this amazing package!
You still have the double delete button probleme for the case of a HasMany field in a resource.
I don't know how to fix it! Thanks
image

**Pull request merged**
